### ISSUE TITLE
USB connection lost

### ISSUE THREAD

**Issue by mahnu** [amfitech/amfiprot#6]
First of all thanks for providing this package!

I have a USB connection problem and would like to know if you can help me.

I am using the amfitrack on Linux:

```bash
$ python --version
Python 3.12.3
$ pip list
Package            Version
------------------ --------
amfiprot           0.1.11
amfiprot_amfitrack 0.0.1a14
cobs               1.2.1
crcmod             1.7
libusb-package     1.0.26.1
pip                24.0
pyserial           3.5
pyusb              1.2.1
```

Here is what I get when I try to run `python ./amfiprot/examples/read_config.py `:
```bash
USB device: Amfitrack Hub (206833693831)
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Traceback (most recent call last):
  File "/home/demo/git/./amfiprot/examples/read_config.py", line 23, in <module>
    cfg = dev.config.read_all()
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/demo/venv/lib/python3.12/site-packages/amfiprot/configurator.py", line 13, in read_all
    for cat_index in range(self._get_category_count()):
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/demo/venv/lib/python3.12/site-packages/amfiprot/configurator.py", line 86, in _get_category_count
    packet = self.device._await_packet(ReplyCategoryCountPayload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/demo/venv/lib/python3.12/site-packages/amfiprot/device.py", line 120, in _await_packet
    raise TimeoutError("Packet not returned.")
TimeoutError: Packet not returned.
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
```

Few months ago, everything worked very well. 
Any idea of how I can deal with this problem?

**Comment by mahnu** [comment]
I just try with previous versions of the amfitrack package and managed to get it working again using 0.1.8
(`pip install --force-reinstall -v "amfiprot==0.1.8"`).
All version > 0.1.8 don't seem to work.

I will use version 0.1.8 as a workaround from now on.

**Comment by darioSez** [comment]
```
$ python --version   
Python 3.12.6

$ pip list        
Package                 Version
----------------------- -----------
absl-py                 2.1.0
AHRS                    0.3.1
amfiprot                0.1.8
amfiprot_amfitrack      0.0.1a14
annotated-types         0.7.0
anyio                   4.6.2.post1
appnope                 0.1.4
```

```
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
Write Task Reconnecting...
Write Task Connection re-established!
Write Task USB connection lost.
```

I am reporting the exact same issue as above, even after downgrading to 0.1.8. 

please advise, thank you!

**Comment by ds-amfitech** [comment]
> ```
> $ python --version   
> Python 3.12.6
> 
> $ pip list        
> Package                 Version
> ----------------------- -----------
> absl-py                 2.1.0
> AHRS                    0.3.1
> amfiprot                0.1.8
> amfiprot_amfitrack      0.0.1a14
> annotated-types         0.7.0
> anyio                   4.6.2.post1
> appnope                 0.1.4
> ```
> 
> ```
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> Write Task Reconnecting...
> Write Task Connection re-established!
> Write Task USB connection lost.
> ```
> 
> I am reporting the exact same issue as above, even after downgrading to 0.1.8.
> 
> please advise, thank you!

If you see the same exact output after downgrading to 0.1.8, then the downgrade has not gone right, because the debug text has been added in a later version.

We are currently working on a fix for running version >0.1.8 on Linux and macOS, and expect to have a new version ready early next week.

**Comment by AmfitechTorkil** [comment]
Amfiprot version 0.1.12 is now live. This new version should fix this issue on Linux and macOS.

**Comment by mahnu** [comment]
Thank you very much!

I confirm that version 0.1.12 fix this issue on Linux (Ubuntu 24.04.2 LTS, kernel 6.8.0-53-generic).
From my point of view, you may close this issue.
